#!/usr/bin/env python3
"""Deterministic App Server fixture. Only reads credentials generated by tests."""
import json
import os
import pathlib
import sys

home = pathlib.Path(os.environ["CODEX_HOME"])
fixture = pathlib.Path(os.environ["CCSW_MOCK_AUTH"])

def emit(value):
    print(json.dumps(value), flush=True)

for line in sys.stdin:
    request = json.loads(line)
    method = request.get("method")
    if "id" not in request:
        continue
    request_id = request["id"]
    result = {}
    if method == "account/login/start":
        auth = json.loads(fixture.read_text())
        (home / "auth.json").write_text(json.dumps(auth))
        # Completion can precede the response; CCSW must retain it.
        emit({"method": "account/login/completed", "params": {"loginId": "test-login", "success": True}})
        result = {"type": "chatgptDeviceCode", "loginId": "test-login", "verificationUrl": "https://auth.openai.com/codex/device", "userCode": "TEST-CODE"}
    elif method == "account/read":
        auth = json.loads((home / "auth.json").read_text())
        auth["tokens"]["refresh_token"] = "refreshed-in-fixture"
        (home / "auth.json").write_text(json.dumps(auth))
        result = {"account": {"type": "chatgpt", "email": "a@example.test", "planType": "plus"}}
    elif method == "account/rateLimits/read":
        if fixture.with_suffix(".fail").exists():
            emit({"id": request_id, "error": {"code": -1, "message": "SECRET_SHOULD_NEVER_BE_LOGGED"}})
            continue
        result = {"rateLimits": {"primary": {"usedPercent": 25, "windowDurationMins": 300, "resetsAt": 2000000000}, "secondary": None}, "rateLimitsByLimitId": None}
    emit({"id": request_id, "result": result})
